TestMasterDetail/TestMasterDetail/Controllers/TeamMembersController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestMasterDetail.DataAccess;
using TestMasterDetail.Models;

namespace TestMasterDetail.Controllers
{
   public class TeamMembersController : Controller
   {

      private readonly AppDbContext db;

      public TeamMembersController(AppDbContext db)
      {
         this.db = db;
      }

      /*public IActionResult Index()
      {
         return View();
      }
      */

      [HttpPost]
      public IActionResult List(int teamId)
      {
         MasterDetailViewModel model = new MasterDetailViewModel
         {
            Teams = db.Teams.ToList(),
            SelectedTeam = db.Teams.Find(teamId),
            DataEntryTarget = DataEntryTargets.TeamMembers,
            DataDisplayMode = DataDisplayModes.Read
         };

         db.Entry(model.SelectedTeam).Collection(team => team.Members).Load();

         return View("Main", model);
      }

      [HttpPost]
      public IActionResult Select(int teamId, int memberId)
      {
         MasterDetailViewModel model = new MasterDetailViewModel
         {
            Teams = db.Teams.ToList(),
            SelectedTeam = db.Teams.Find(teamId),
            SelectedTeamMember = db.TeamMembers.Find(memberId),
            DataEntryTarget = DataEntryTargets.TeamMembers,
            DataDisplayMode = DataDisplayModes.Read
         };

         db.Entry(model.SelectedTeam).Collection(team => team.Members).Load();

         return View("Main", model);
      }

      [HttpPost]
      public IActionResult InsertEntry(int teamId)
      {
         MasterDetailViewModel model = new MasterDetailViewModel
         {
            Teams = db.Teams.ToList(),
            SelectedTeam = db.Teams.Find(teamId),
            SelectedTeamMember = null,
            DataEntryTarget = DataEntryTargets.TeamMembers,
            DataDisplayMode = DataDisplayModes.Insert
         };

         db.Entry(model.SelectedTeam).Collection(team => team.Members).Load();
         return View("Main", model);
      }

      [HttpPost]
      public IActionResult InsertSave(TeamMember member)
      {
         db.TeamMembers.Add(member);
         db.SaveChanges();
         
         MasterDetailViewModel model = new MasterDetailViewModel
         {
            Teams = db.Teams.ToList(),
            SelectedTeam = db.Teams.Find(member.TeamID),
            //SelectedTeamMember = db.TeamMembers.Find(member.TeamMemberID),
            SelectedTeamMember = null,
            DataEntryTarget = DataEntryTargets.TeamMembers,
            DataDisplayMode = DataDisplayModes.Read
         };

         db.Entry(model.SelectedTeam).Collection(team => team.Members).Load();
         return View("Main", model);
      }

      [HttpPost]
      public IActionResult UpdateEntry(int teamId, int memberId)
      {
         MasterDetailViewModel model = new MasterDetailViewModel
         {
            Teams = db.Teams.ToList(),
            SelectedTeam = db.Teams.Find(teamId),
            SelectedTeamMember = db.TeamMembers.Find(memberId),
            DataEntryTarget = DataEntryTargets.TeamMembers,
            DataDisplayMode = DataDisplayModes.Update
         };

         db.Entry(model.SelectedTeam).Collection(team => team.Members).Load();
         return View("Main", model);
      }

      [HttpPost]
      public IActionResult UpdateSave(TeamMember member)
      {
         db.TeamMembers.Update(member);
         db.SaveChanges();

         MasterDetailViewModel model = new MasterDetailViewModel
         {
            Teams = db.Teams.ToList(),
            SelectedTeam = db.Teams.Find(member.TeamID),
            SelectedTeamMember = db.TeamMembers.Find(member.TeamMemberID),
            DataEntryTarget = DataEntryTargets.TeamMembers,
            DataDisplayMode = DataDisplayModes.Read
         };

         db.Entry(model.SelectedTeam).Collection(team => team.Members).Load();

         return View("Main", model);
      }

      [HttpPost]
      public IActionResult CancelEntry(int teamId)
      {
         MasterDetailViewModel model = new MasterDetailViewModel
         {
            Teams = db.Teams.ToList(),
            SelectedTeam = db.Teams.Find(teamId),
            SelectedTeamMember = null,
            DataEntryTarget = DataEntryTargets.TeamMembers,
            DataDisplayMode = DataDisplayModes.Read
         };

         db.Entry(model.SelectedTeam).Collection(team => team.Members).Load();

         return View("Main", model);
      }

      [HttpPost]
      public IActionResult CancelSelection(int teamId)
      {
         MasterDetailViewModel model = new MasterDetailViewModel
         {
            Teams = db.Teams.ToList(),
            SelectedTeam = db.Teams.Find(teamId),
            SelectedTeamMember = null,
            DataEntryTarget = DataEntryTargets.TeamMembers,
            DataDisplayMode = DataDisplayModes.Read
         };

         db.Entry(model.SelectedTeam).Collection(team => team.Members).Load();

         return View("Main", model);
      }

      [HttpPost]
      public IActionResult Delete(int teamId, int memberId)
      {
         TeamMember member = db.TeamMembers.Find(memberId);
         db.TeamMembers.Remove(member);
         db.SaveChanges();

         MasterDetailViewModel model = new MasterDetailViewModel
         {
            Teams = db.Teams.ToList(),
            SelectedTeam = db.Teams.Find(teamId),
            SelectedTeamMember = null,
            DataEntryTarget = DataEntryTargets.TeamMembers,
            DataDisplayMode = DataDisplayModes.Read
         };

         db.Entry(model.SelectedTeam).Collection(team => team.Members).Load();

         return View("Main", model);
      }

   }
}

TestMasterDetail/TestMasterDetail/Views/TeamMembers/_InsertTeamMember.cshtml
@using TestMasterDetail.DataAccess
@model TeamMember

<h2>Insert New Team Member</h2>

<form method="post">

   <input type="hidden" asp-for="TeamID" />

   <table border="1" cellpadding="10">
      <tr>
         <td>Name :</td>
         <td><input type="text" asp-for="Name" /></td>
      </tr>
      <tr>
         <td>Email :</td>
         <td><input type="text" asp-for="Email" /></td>
      </tr>
      <tr>
         <td colspan="2">
            <input type="submit"
                   value="Save"
                   asp-controller="TeamMembers"
                   asp-action="InsertSave"
                   asp-route-teamid="@Model.TeamID" />

            <input type="submit"
                   value="Cancel"
                   asp-controller="TeamMembers"
                   asp-action="CancelEntry"
                   asp-route-teamid="@Model.TeamID" />
         </td>
      </tr>
   </table>
</form>

TestMasterDetail/TestMasterDetail/Views/TeamMembers/_ShowTeamMember.cshtml
@using TestMasterDetail.DataAccess
@model TeamMember


<h2>Edit Team Member : @Model.Name</h2>

<form method="post">
   <table border="1" cellpadding="10">
      <tr>
         <td>Team ID :</td>
         <td>@Model.TeamID</td>
      </tr>
      <tr>
         <td>Team Member ID :</td>
         <td>@Model.TeamMemberID</td>
      </tr>
      <tr>
         <td>Name :</td>
         <td>@Model.Name</td>
      </tr>
      <tr>
         <td>Email :</td>
         <td>@Model.Email</td>
      </tr>
      <tr>
         <td colspan="2">
            <input type="submit"
                   value="Edit"
                   asp-controller="TeamMembers"
                   asp-action="UpdateEntry"
                   asp-route-teamid="@Model.TeamID"
                   asp-route-memberid="@Model.TeamMemberID" />

            <input type="submit"
                   value="Delete"
                   asp-controller="TeamMembers"
                   asp-action="Delete"
                   asp-route-teamid="@Model.TeamID"
                   asp-route-memberid="@Model.TeamMemberID" />

            <input type="submit"
                   value="Cancel"
                   asp-controller="TeamMembers"
                   asp-action="CancelSelection"
                   asp-route-teamid="@Model.TeamID" />
         </td>
      </tr>
   </table>
</form>

TestMasterDetail/TestMasterDetail/Views/TeamMembers/_UpdateTeamMember.cshtml
@using TestMasterDetail.DataAccess
@model TeamMember

<h2>Edit Team Member : @Model.Name</h2>

<form method="post">
   <table border="1" cellpadding="10">
      <tr>
         <td>Team ID :</td>
         <td>
            <input type="text" asp-for="TeamID" readonly />
         </td>
      </tr>
      <tr>
         <td>Team Member ID :</td>
         <td>
            <input type="text" asp-for="TeamMemberID" readonly />
         </td>
      </tr>
      <tr>
         <td>Name :</td>
         <td><input type="text" asp-for="Name" /></td>
      </tr>
      <tr>
         <td>Email :</td>
         <td><input type="text" asp-for="Email" /></td>
      </tr>
      <tr>
         <td colspan="2">
            <input type="submit"
                   value="Save"
                   asp-controller="TeamMembers"
                   asp-action="UpdateSave"
                   asp-route-teamid="@Model.TeamID"
                   asp-route-memberid="@Model.TeamMemberID" />

            <input type="submit"
                   value="Cancel"
                   asp-controller="TeamMembers"
                   asp-action="CancelEntry"
                   asp-route-teamid="@Model.TeamID"
                   asp-route-memberid="@Model.TeamMemberID" />
         </td>
      </tr>
   </table>
</form>